export const STACK = [
  {
    id: "html-css",
    name: "HTML & CSS",
    icon: "🌍",
    category: "Foundation",
    categoryColor: "#ff6b35",
    level: 95,
    priority: "CRITICAL",
    tagline: "The skeleton and skin of everything on the web.",
    what: "HTML (HyperText Markup Language) is the structure of every webpage — headings, paragraphs, buttons, forms, images. CSS (Cascading Style Sheets) is what makes it look good — colors, fonts, layouts, animations. Every website, web app, and tool you build starts here. React itself compiles down to HTML/CSS in the end.",
    who: "Invented by Tim Berners-Lee in 1991. Used by literally every website on earth. 100% of browsers understand HTML/CSS natively — no installation, no framework, no build step needed.",
    how: "Write .html files with tags like <div>, <h1>, <button>. Style them in .css files with selectors and properties. Even when using React or Tailwind, you need to READ and DEBUG the HTML/CSS output. For OSINT: you read HTML to find data patterns on websites. For scraping: you target HTML elements. For emails: lead gen emails are pure HTML/CSS. For games: CSS animations make things move for free.",
    tools: ["VS Code + Live Server extension (instant preview)", "Chrome DevTools (F12 — inspect any website)", "Emmet (type shortcuts, get full HTML)", "CSS Flexbox/Grid (modern layouts)"],
    resources: ["developer.mozilla.org (MDN — the bible)", "css-tricks.com", "flexboxfroggy.com (learn flexbox by playing)", "cssgridgarden.com (learn grid by playing)", "web.dev/learn"],
    usedFor: ["Landing pages (NexusGuard)", "Email templates for lead gen", "Reading scraped pages for OSINT", "Game UI and animations", "Any web thing ever"],
    timeToLearn: "Basic HTML: 2 days. CSS layouts: 1 week. Confident: 2-3 weeks.",
    command: "<!-- No install needed. Create index.html and open in browser -->",
    install: "Zero install. Create a .html file. Open in Chrome. Done.",
    color: "#ff6b35",
    whyYouNeedIt: "When AI generates broken layouts or your React component looks wrong — you need to open DevTools and READ the HTML/CSS to fix it. Without this, you're blind to your own output. Also: NexusGuard's landing page, your game UIs, your lead gen email templates — all HTML/CSS."
  },
  {
    id: "python",
    name: "Python",
    icon: "🐍",
    category: "Core Language",
    categoryColor: "#00e5a0",
    level: 100,
    priority: "CRITICAL",
    tagline: "Your single most important skill. The language of AI.",
    what: "A programming language that reads like plain English. Created in 1991 by Guido van Rossum. Now the #1 language for AI/ML, automation, data processing, OSINT tools, and backend APIs. Has more libraries than any other language — if you can think of a task, there's a Python package for it.",
    who: "Used by Google, NASA, Netflix, Instagram, every AI lab on earth. OpenAI, Anthropic, DeepMind all use Python as their primary language. The language of the AI era — non-negotiable.",
    how: "Write .py files and run them from terminal. Use pip to install packages. Build scripts that automate tasks, call AI APIs, scrape websites, process data, run as backend servers. Every automation tool, OSINT script, voice agent backend, and AI integration you build will use Python.",
    tools: ["pip (package installer)", "virtualenv / venv (isolate project dependencies)", "Jupyter Notebook (experiments and data work)", "VS Code + Python extension", "pyenv (manage multiple Python versions)"],
    resources: ["python.org/tutorial (official)", "automatetheboringstuff.com (free book — perfect for you)", "realpython.com", "docs.python.org", "learnpython.org"],
    usedFor: ["AI integrations (OpenAI, Anthropic APIs)", "Automation scripts", "OSINT tools", "Web scraping", "Backend APIs", "Workflow automation", "Data processing", "OSS tools"],
    timeToLearn: "Shipping simple scripts: 2 weeks. Comfortable: 1-2 months. Master: ongoing forever.",
    command: "python --version\npip install requests openai langchain",
    install: "python.org → Downloads → Install Python 3.12+ → Check 'Add to PATH'",
    color: "#00e5a0",
    whyYouNeedIt: "Everything AI-related runs on Python. Your OSINT tools, automation workflows, voice agent backends, scrapers — all Python. The AI libraries (LangChain, OpenAI SDK, Whisper) are Python-first. If you only master one language deeply, make it this."
  },
  {
    id: "javascript",
    name: "JavaScript",
    icon: "⚡",
    category: "Core Language",
    categoryColor: "#00e5a0",
    level: 90,
    priority: "CRITICAL",
    tagline: "The only language that runs natively in every browser.",
    what: "JavaScript is the programming language of the web. It makes websites interactive — button clicks, form validation, API calls, animations, real-time updates. Every browser runs JS natively. Also runs on servers via Node.js. You can't build web tools without understanding it.",
    who: "Created by Brendan Eich in 10 days in 1995. Now the most used programming language in the world (Stack Overflow survey every year). Every web framework (React, Vue, Next.js) is built on JavaScript.",
    how: "Write JS inside HTML <script> tags or in .js files. Use it to handle user interactions, call APIs (fetch), manipulate the page (DOM), validate forms. Node.js lets you run JS on your server. You don't need to memorize everything — you need to READ and DEBUG what AI generates.",
    tools: ["Browser DevTools Console (F12 → Console tab)", "Node.js (run JS outside browser)", "npm (package manager)", "ESLint (catch errors)", "Prettier (auto-format code)"],
    resources: ["javascript.info (best free JS course)", "developer.mozilla.org/javascript", "eloquentjavascript.net (free book)", "node.js.org/docs"],
    usedFor: ["Web app interactivity", "API calls from frontend", "React (built on JS)", "Browser automation", "Node.js scripts", "Game logic"],
    timeToLearn: "Basics: 2 weeks. Comfortable with async/fetch: 1 month.",
    command: "node --version\nnpm --version",
    install: "nodejs.org → Download LTS → Install (includes npm automatically)",
    color: "#f7df1e",
    whyYouNeedIt: "React is JavaScript. Every web tool is JavaScript. When AI generates a broken fetch() call or a broken event handler, you need to read the JS to fix it. Also: your learning games need JS for game logic, your web tools need JS for interactivity."
  },
  {
    id: "react",
    name: "React + Tailwind",
    icon: "⚛️",
    category: "Web Frontend",
    categoryColor: "#7eb8ff",
    level: 90,
    priority: "CRITICAL",
    tagline: "Build every web UI, SaaS dashboard, and tool frontend.",
    what: "React is a JavaScript library by Meta for building UIs with reusable components. Instead of writing HTML pages, you write components (Header, Button, Card, Dashboard) that React assembles. Tailwind CSS is a utility-first framework — instead of writing CSS, you add classes like 'text-lg font-bold bg-blue-500' directly in your HTML.",
    who: "React built by Facebook/Meta, open sourced 2013. Used by Airbnb, Netflix, Notion, Dropbox, NexusGuard. 22M+ GitHub stars. Tailwind used by 40%+ of new web projects in 2026.",
    how: "Create components as JavaScript functions that return JSX (HTML-like syntax). Pass data via props. Manage state with useState. Fetch data with useEffect. Tailwind: add utility classes to elements. AI writes 90% of React — you need to understand components, state, and props to direct AI and debug output.",
    tools: ["Vite (fastest project setup)", "React DevTools browser extension", "shadcn/ui (beautiful component library)", "Framer Motion (animations)", "React Router (multiple pages)"],
    resources: ["react.dev (official — excellent)", "tailwindcss.com/docs", "ui.shadcn.com", "vitejs.dev/guide"],
    usedFor: ["NexusGuard frontend", "SaaS product UIs", "Web tool interfaces", "Dashboards", "Landing pages with interactivity"],
    timeToLearn: "Mental model: 1 week. First real app: 2-3 weeks.",
    command: "npm create vite@latest my-app -- --template react\ncd my-app && npm install\nnpm install -D tailwindcss postcss autoprefixer",
    install: "Comes with Vite. Tailwind: npm install -D tailwindcss",
    color: "#7eb8ff",
    whyYouNeedIt: "Every SaaS UI you build will be React. This Stack Bible app is React. NexusGuard's dashboard will be React. It's the industry standard and AI generates React better than any other framework."
  },
  {
    id: "reactnative",
    name: "React Native + Expo",
    icon: "📱",
    category: "Mobile",
    categoryColor: "#ff6b35",
    level: 88,
    priority: "CRITICAL",
    tagline: "One codebase. Ships to iOS and Android. No compromise.",
    what: "React Native lets you write mobile apps using React (JavaScript) that compile to REAL native iOS and Android apps — not a web wrapper. Expo is a toolkit on top that removes all painful setup: no Xcode configuration, no Android Studio nightmares, just code and run.",
    who: "Built by Meta. Used by Facebook, Instagram, Shopify, Discord, Walmart. Expo used by 700k+ developers. The dominant cross-platform mobile framework in 2026.",
    how: "Write React components — React Native maps them to native elements (View = div, Text = p, TouchableOpacity = button). Expo Go app lets you scan a QR code and instantly see your app on your real phone. EAS Build creates App Store / Play Store ready builds in the cloud.",
    tools: ["Expo Go (test on phone instantly — scan QR)", "EAS Build (cloud builds for stores)", "Expo Router (file-based navigation)", "NativeWind (Tailwind for mobile)", "React Native Debugger"],
    resources: ["expo.dev/learn", "reactnative.dev/docs/getting-started", "docs.expo.dev", "nativewind.dev"],
    usedFor: ["iOS apps", "Android apps", "Mobile versions of your tools", "Learning games on mobile", "Region-specific mobile products"],
    timeToLearn: "1 week if you know React. 3 weeks from zero.",
    command: "npx create-expo-app@latest my-mobile-app\ncd my-mobile-app && npx expo start",
    install: "Node.js installed → run create-expo-app command → install Expo Go on your phone",
    color: "#ff6b35",
    whyYouNeedIt: "You said you build mobile apps. Without React Native you need to learn Swift (iOS) AND Kotlin (Android) separately — months of work. React Native gives you both with skills you already have."
  },
  {
    id: "fastapi",
    name: "FastAPI",
    icon: "🚀",
    category: "Backend",
    categoryColor: "#ff6b35",
    level: 88,
    priority: "CRITICAL",
    tagline: "Python backend. Powers all your APIs and AI services.",
    what: "A modern Python web framework for building APIs extremely fast. It auto-generates interactive documentation, handles data validation automatically, supports async operations, and is purpose-built for AI-era backends. The fastest Python web framework available.",
    who: "Created by Sebastián Ramírez in 2018. Used by Microsoft, Uber, Netflix for internal tools. Became the #1 Python API framework by 2024. Powers most serious Python AI products.",
    how: "Define Python functions with decorators (@app.get, @app.post). FastAPI handles routing, validation, serialization. Connect to Supabase for data, Redis for queues, LangChain for AI. Expose your Python scripts as HTTP endpoints that your React frontend or mobile app can call.",
    tools: ["Uvicorn (ASGI server)", "Pydantic (automatic data validation)", "SQLAlchemy (database ORM)", "python-dotenv (environment variables)", "httpx (async HTTP client)"],
    resources: ["fastapi.tiangolo.com (incredible official docs)", "testdriven.io/courses/tdd-fastapi", "realpython.com/fastapi-python-web-apis"],
    usedFor: ["Voice agent backend", "AI tool APIs", "NexusGuard audit engine backend", "Automation trigger endpoints", "OSINT tool APIs"],
    timeToLearn: "First working API: same day. Productive: 3 days.",
    command: "pip install fastapi uvicorn python-dotenv\nuvicorn main:app --reload",
    install: "pip install fastapi uvicorn",
    color: "#ff6b35",
    whyYouNeedIt: "Your Python AI tools need a way to talk to your React frontend and mobile app. FastAPI is that bridge. Voice agents need a real-time backend — FastAPI + WebSockets is the stack."
  },
  {
    id: "supabase",
    name: "Supabase",
    icon: "🗄️",
    category: "Database & Auth",
    categoryColor: "#00e5a0",
    level: 90,
    priority: "CRITICAL",
    tagline: "Full backend in one. Database + Auth + Storage + Realtime.",
    what: "Open source Firebase alternative. Gives you a PostgreSQL database (real SQL, not NoSQL), user authentication (email, Google, GitHub login), file storage, and real-time subscriptions — all with a beautiful visual dashboard and zero server management. Free tier is extremely generous.",
    who: "Founded 2020, backed by Y Combinator, Mozilla, Coatue. $200M+ funding. 70k+ GitHub stars. Used by 1M+ developers. Open source — you can self-host it for your OSS projects.",
    how: "Create project at supabase.com → get URL and API keys → use JS SDK in React/React Native or Python SDK in FastAPI. Create tables visually or with SQL. Auth handles entire login flow. Storage handles file uploads. Realtime lets you stream live data to users.",
    tools: ["@supabase/supabase-js (JS SDK)", "supabase-py (Python SDK)", "Supabase CLI (local development)", "pgAdmin (advanced DB management)", "Row Level Security (user data isolation)"],
    resources: ["supabase.com/docs", "supabase.com/docs/guides/getting-started/quickstarts/reactjs", "egghead.io/courses/build-a-saas-product-with-next-js-supabase"],
    usedFor: ["User authentication for all products", "NexusGuard customer database", "File uploads for audit reports", "Mobile app backend", "OSS self-hosted projects"],
    timeToLearn: "First query working: same day. Auth integrated: 2-3 days.",
    command: "npm install @supabase/supabase-js\n# Python: pip install supabase",
    install: "supabase.com → Sign up → New project → Copy URL and anon key",
    color: "#00e5a0",
    whyYouNeedIt: "Every product you build needs a database and user auth. Supabase replaces months of backend setup with 30 minutes of config. Works with React, React Native, AND Python."
  },
  {
    id: "langchain",
    name: "LangChain",
    icon: "🔗",
    category: "AI Framework",
    categoryColor: "#b388ff",
    level: 92,
    priority: "CRITICAL",
    tagline: "Chain LLMs, memory, tools, and data into real AI products.",
    what: "A Python/JavaScript framework for building applications powered by LLMs. Goes way beyond simple API calls — it adds memory (AI remembers previous messages), tools (AI can take actions), document loading (connect your own data), and chains (multi-step AI workflows). This is how serious AI products are built.",
    who: "Most starred AI engineering repo on GitHub. Created by Harrison Chase in Oct 2022. Now 90k+ GitHub stars. Used by every serious AI startup. LangSmith (their tracing tool) is the industry standard for debugging AI apps.",
    how: "Install langchain + your LLM provider. Create a chain: LLM + prompt template + output parser. Add memory so conversations are stateful. Add retrieval to connect your documents. Add tools so AI can call functions, search web, query databases. Build agents that decide which tools to use autonomously.",
    tools: ["LangSmith (trace and debug AI calls)", "FAISS / Chroma (vector databases for documents)", "LangServe (deploy chains as APIs)", "LangGraph (complex agent workflows)", "OpenAI / Anthropic / Groq SDKs"],
    resources: ["python.langchain.com/docs", "github.com/langchain-ai/langchain", "smith.langchain.com (LangSmith)", "learnlangchain.pages.dev"],
    usedFor: ["NexusGuard AI audit engine", "Voice agent conversation brain", "OSINT AI analysis", "Document Q&A tools", "Multi-step AI automation"],
    timeToLearn: "Basic chains: 3 days. Agents: 1-2 weeks. Advanced: ongoing.",
    command: "pip install langchain langchain-openai langchain-anthropic\npip install langchain-community faiss-cpu",
    install: "pip install langchain + your preferred LLM provider package",
    color: "#b388ff",
    whyYouNeedIt: "Without LangChain you're limited to single API calls. With it you can build AI that remembers, reasons across your documents, uses tools, and completes multi-step tasks. NexusGuard's audit AI needs exactly this."
  },
  {
    id: "voice",
    name: "ElevenLabs + Whisper + Twilio",
    icon: "🎙️",
    category: "Voice Stack",
    categoryColor: "#ff6b35",
    level: 85,
    priority: "CRITICAL",
    tagline: "The complete voice agent pipeline. All 3 work together.",
    what: "Three tools that together build a complete voice agent: ElevenLabs converts text to hyper-realistic AI voice (text-to-speech). OpenAI Whisper converts speech to text (speech-to-text / transcription). Twilio handles phone infrastructure — making and receiving real phone calls, SMS, and WhatsApp at scale.",
    who: "ElevenLabs: founded 2022, $3B valuation, 1M+ users. Used for AI dubbing, voice assistants. Whisper: open source from OpenAI, the most accurate transcription model available. Twilio: $10B+ company, powers 10M+ developers' communication apps.",
    how: "The voice agent loop: User calls your Twilio number → Twilio streams audio to your FastAPI server → Whisper transcribes speech to text in real-time → LangChain processes the intent and generates response text → ElevenLabs converts response text to realistic voice audio → Twilio plays audio back to user. Entire loop under 2 seconds.",
    tools: ["ElevenLabs API + Python SDK", "OpenAI Whisper API (or local model)", "Twilio Voice SDK + TwiML", "FastAPI + WebSockets (real-time audio streaming)", "pydub (audio processing)"],
    resources: ["elevenlabs.io/docs", "platform.openai.com/docs/guides/speech-to-text", "twilio.com/docs/voice/quickstart/python", "github.com/twilio-labs/python-twilio"],
    usedFor: ["AI phone sales agents", "Voice-powered lead generation", "Automated appointment booking", "Customer support voice bots", "Voice-controlled tools"],
    timeToLearn: "Each API alone: 1-2 days. Full pipeline working: 1-2 weeks.",
    command: "pip install elevenlabs openai twilio\npip install fastapi websockets pydub",
    install: "elevenlabs.io (sign up, free tier), platform.openai.com (API key), twilio.com (trial account with free credits)",
    color: "#ff6b35",
    whyYouNeedIt: "You said you build voice agents. This IS the voice agent stack. No alternatives — these three together are the industry standard pipeline."
  },
  {
    id: "n8n",
    name: "n8n + Webhooks",
    icon: "🔄",
    category: "Automation",
    categoryColor: "#ffb347",
    level: 85,
    priority: "HIGH",
    tagline: "Visual workflow automation. Open source. Self-hostable forever.",
    what: "n8n is an open-source workflow automation tool — more powerful than Zapier, and you own it. Connect any two services with visual nodes. Webhooks are HTTP endpoints that trigger your automation when something happens in another service (Stripe payment → trigger onboarding, GitHub push → trigger deployment, Form submit → trigger lead processing).",
    who: "n8n: 50k+ GitHub stars, 50k+ companies using it. Fully open source (fair-code license). Self-host it on Railway, Render, or your own server. Webhooks: used by every modern API — Stripe, GitHub, Shopify, Twilio all send webhooks.",
    how: "Start n8n → drag trigger node (Webhook, Schedule, New Email) → connect action nodes (Send email, Query DB, Call AI, Post to Slack, Update spreadsheet) → activate workflow. For webhooks in Python: @app.post('/webhook') in FastAPI → paste that URL into Stripe or GitHub settings → your code runs automatically when events happen.",
    tools: ["n8n Cloud (easiest start)", "Railway/Render (self-host free)", "ngrok (expose local server for testing webhooks)", "Postman / Insomnia (test webhook endpoints)", "webhook.site (inspect incoming webhooks)"],
    resources: ["docs.n8n.io", "n8n.io/workflows (1000+ templates)", "webhook.site", "ngrok.com/docs"],
    usedFor: ["Client automation workflows", "Lead gen data pipelines", "NexusGuard onboarding automation", "Marketing automation", "OSINT data collection pipelines"],
    timeToLearn: "First workflow: same day. Complex pipelines: 1 week.",
    command: "npx n8n\n# Or Docker: docker run -it --rm --name n8n -p 5678:5678 n8nio/n8n",
    install: "npx n8n (instant, no install) OR n8n.io/cloud (hosted, free tier)",
    color: "#ffb347",
    whyYouNeedIt: "You build automation workflows and tools for clients. n8n lets you build and visualize complex automations without writing boilerplate. Webhooks let every tool talk to every other tool automatically."
  },
  {
    id: "redis",
    name: "Redis + Celery",
    icon: "🔴",
    category: "Automation Backend",
    categoryColor: "#ffb347",
    level: 78,
    priority: "HIGH",
    tagline: "Run thousands of background tasks without freezing or crashing.",
    what: "Redis is an ultra-fast in-memory database used for queues, caching, session storage, and pub/sub messaging. Celery is a Python distributed task queue that runs jobs in the background — your main app stays fast while heavy tasks (scraping 10k pages, sending 500 emails, processing audio files) run asynchronously.",
    who: "Redis: created 2009, used by Twitter, GitHub, Stack Overflow, Airbnb. 60k+ GitHub stars. Available as Redis Cloud (free tier). Celery: the standard Python async task system — used wherever Python apps need background processing.",
    how: "User triggers lead gen scrape for 1000 companies → instead of the web request waiting 10 minutes, you put the job in Celery queue (stored in Redis) → return '202 Accepted' immediately → Celery worker picks up job and runs it in background → saves results to Supabase → sends webhook/email to user when done. User never waits.",
    tools: ["Redis Cloud (free hosted Redis)", "Celery (pip install celery)", "Flower (visual Celery task monitor)", "Redis Insight (visual Redis browser)", "Beat scheduler (cron-like scheduled tasks)"],
    resources: ["redis.io/docs", "docs.celeryq.dev/en/stable/getting-started", "realpython.com/asynchronous-tasks-with-django-and-celery"],
    usedFor: ["Lead gen bulk processing", "OSINT background crawls", "Bulk email campaigns", "Automation pipeline queuing", "Voice agent session management"],
    timeToLearn: "Redis basics: 2 days. Celery working: 3-4 days.",
    command: "pip install celery redis\n# Redis Cloud: redis.io/cloud — free 30MB tier",
    install: "Redis Cloud free at redis.io/cloud OR redis.io/download for local",
    color: "#ff4d6d",
    whyYouNeedIt: "When your lead gen tool needs to process 1000 leads, your OSINT scraper needs to crawl 500 pages, or your voice agent needs to handle multiple concurrent calls — Redis + Celery is how you don't crash."
  },
  {
    id: "leadgen",
    name: "Apollo + Clay + Hunter.io",
    icon: "🎯",
    category: "Lead Generation",
    categoryColor: "#ffb347",
    level: 82,
    priority: "HIGH",
    tagline: "Your revenue engine. Stop building lead databases from scratch.",
    what: "Apollo.io: a database of 275M+ contacts with verified emails, phone numbers, LinkedIn profiles, job titles, company info — all accessible via API. Hunter.io: finds and verifies email addresses for any domain. Clay: modern AI-powered lead enrichment platform that automatically researches leads and writes personalized outreach using AI.",
    who: "Apollo: 160k+ companies, raised $100M+, the go-to B2B contact database. Hunter.io: 4M+ users, trusted for email verification. Clay: fastest growing sales tool in 2025-2026, used by top revenue teams globally, backed by a16z.",
    how: "Apollo API → search contacts by job title + industry + company size + location → get emails and phones → export to Clay → Clay AI enriches each lead (visits their website, LinkedIn, generates personalized message) → Hunter.io verifies emails → push verified leads + messages to email tool (Instantly, Lemlist) → n8n automates the entire pipeline. Full outbound machine on autopilot.",
    tools: ["Apollo.io API", "Hunter.io API", "Clay (clayhq.com)", "Instantly.ai (email sending at scale)", "Lemlist (personalized outreach)", "Python requests (API glue)"],
    resources: ["apollo.io/api-docs", "hunter.io/api-documentation", "clay.com/university", "instantly.ai/docs"],
    usedFor: ["NexusGuard client acquisition", "Lead gen as a service product", "Automated outreach campaigns", "Building lead gen tools for clients"],
    timeToLearn: "Each API: 2-3 days. Full pipeline: 1 week.",
    command: "pip install requests\n# Use REST APIs directly with requests library",
    install: "apollo.io (free tier: 50 credits/month), hunter.io (free: 25 searches/month), clay.com (free trial)",
    color: "#ffb347",
    whyYouNeedIt: "You run lead generation. This is the exact stack serious lead gen operators use in 2026. Building your own contact database from scratch would take years. These APIs give you instant access."
  },
  {
    id: "git",
    name: "Git + GitHub",
    icon: "📦",
    category: "OSS & Version Control",
    categoryColor: "#00e5a0",
    level: 95,
    priority: "CRITICAL",
    tagline: "Your code backup, portfolio, and OSS distribution channel.",
    what: "Git is a version control system — it tracks every change you make to code so you can go back in time, work on features without breaking the main code, and collaborate. GitHub is the platform where code lives publicly or privately online. For OSS builders, GitHub IS your distribution channel — stars mean users, forks mean community.",
    who: "Git created by Linus Torvalds (Linux creator) in 2005. GitHub bought by Microsoft for $7.5B in 2018. 100M+ developers on GitHub. Every OSS project in existence lives here.",
    how: "git init (start tracking) → write code → git add . (stage changes) → git commit -m 'what you did' (save snapshot) → git push (upload to GitHub). For OSS: write excellent README.md, add LICENSE file (MIT for open use), create GitHub Releases for versions, use GitHub Actions for automated testing. GitHub Pages = free website hosting for your projects.",
    tools: ["Git CLI (command line)", "GitHub Desktop (visual, easier for beginners)", "GitHub Actions (automate testing + deployment)", "GitHub Pages (free static hosting)", "Shields.io (readme badges for stars, version, etc)"],
    resources: ["docs.github.com/en/get-started", "learngitbranching.js.org (interactive)", "githubskillseries.github.io", "choosealicense.com"],
    usedFor: ["All project version control", "OSS tool publishing and distribution", "Free static site hosting (GitHub Pages)", "Automated deployment to Netlify/Vercel", "Collaboration and contributions"],
    timeToLearn: "Basic push/pull: 1 day. Branching workflow: 3 days.",
    command: "git init\ngit add .\ngit commit -m 'first commit'\ngit remote add origin https://github.com/yourusername/repo.git\ngit push -u origin main",
    install: "git-scm.com → Download → Install → git config --global user.name 'Your Name'",
    color: "#00e5a0",
    whyYouNeedIt: "You do OSS. GitHub is your storefront. Every tool you ship should be on GitHub. Stars = social proof = more users. Also: Netlify and Vercel deploy directly from GitHub — push code, auto-deploy. Without Git you have no backup and no distribution."
  },
  {
    id: "stripe",
    name: "Stripe",
    icon: "💳",
    category: "Payments",
    categoryColor: "#7eb8ff",
    level: 85,
    priority: "HIGH",
    tagline: "Get paid globally in 2-3 days of integration.",
    what: "The world's best payment infrastructure API. Handles one-time payments, subscriptions (monthly/yearly), usage-based billing, invoices, global currencies (135+), automatic tax calculation, fraud detection, and payouts — all via a clean API. Stripe Checkout is a pre-built payment page you can redirect users to in 10 lines of code.",
    who: "Founded 2010 by Patrick and John Collison (Irish brothers). Valued at $65B. Powers Shopify, Lyft, Zoom, Amazon, Salesforce. Available in 46+ countries. Developers' favorite payment tool by far.",
    how: "Create Stripe account → get test API keys → install SDK → create a Checkout Session with your product price → redirect user to Stripe's hosted page → user pays → Stripe redirects back to your success page → Stripe sends webhook event (payment_intent.succeeded) → your FastAPI endpoint receives it → unlock feature for user in Supabase.",
    tools: ["Stripe Dashboard (visual transaction management)", "Stripe CLI (test webhooks locally)", "stripe Python SDK", "stripe-js (frontend SDK)", "Stripe Customer Portal (let users manage subscriptions)"],
    resources: ["stripe.com/docs/checkout/quickstart", "stripe.com/docs/webhooks", "stripe.com/docs/billing/subscriptions/overview"],
    usedFor: ["NexusGuard audit payments ($1490 / $4900 tiers)", "SaaS subscription billing", "One-time tool purchases", "Lead gen service payments"],
    timeToLearn: "First test payment: same day. Webhooks working: 2-3 days.",
    command: "pip install stripe\n# JS: npm install stripe @stripe/stripe-js",
    install: "stripe.com → Create account → Get API keys from Dashboard",
    color: "#7eb8ff",
    whyYouNeedIt: "NexusGuard needs payments NOW. Every SaaS you build needs payments. Stripe works in Bangladesh via international cards. Without Stripe you can't charge for anything."
  },
  {
    id: "cursor",
    name: "Cursor / Windsurf",
    icon: "🤖",
    category: "AI IDE",
    categoryColor: "#b388ff",
    level: 98,
    priority: "CRITICAL",
    tagline: "Your daily driver. Write less code. Ship 5x faster.",
    what: "AI-native code editors built on VS Code. Not just autocomplete — they understand your entire codebase context. Cursor: press Ctrl+K to generate code from description, Ctrl+L to chat about your codebase, Tab to accept completions. Composer mode edits multiple files simultaneously. Windsurf: similar features, sometimes faster.",
    who: "Cursor by Anysphere — raised $900M at $9B valuation in 2025. Used by 500k+ developers. Windsurf by Codeium — 1M+ users. Both built on VS Code so all your VS Code extensions work.",
    how: "Open your project → Ctrl+L to open chat: 'Add a login form with Supabase auth to this component' → AI writes it with full context of your codebase → Tab to accept → Ctrl+K in the editor to edit selected code inline → use Composer for features that touch many files → use @ to reference specific files in your prompts.",
    tools: ["Cursor (cursor.sh) — recommended", "Windsurf (codeium.com/windsurf) — free alternative", "Claude Sonnet 4.5 or GPT-4o as the AI model", "Cursor Rules (.cursorrules file — gives AI context about your project)", "MCP servers (connect AI to your tools)"],
    resources: ["cursor.sh/docs", "docs.codeium.com/windsurf", "cursor.directory (community cursor rules)"],
    usedFor: ["All coding across all projects", "Generating boilerplate fast", "Debugging complex errors", "Understanding unfamiliar codebases", "Refactoring old code"],
    timeToLearn: "Productive on day 1. Mastery: 2-3 weeks of daily use.",
    command: "# Just download and open your existing project folder",
    install: "cursor.sh → Download → Install → Open project (replaces VS Code)",
    color: "#b388ff",
    whyYouNeedIt: "You already use AI to code. Cursor puts that AI directly inside your editor with full codebase context. It's the difference between describing your problem to AI in a chat window vs having AI as a co-pilot inside the code."
  },
  {
    id: "docker",
    name: "Docker",
    icon: "🐳",
    category: "Deployment",
    categoryColor: "#ffb347",
    level: 72,
    priority: "HIGH",
    tagline: "Ship your tools anywhere. Works on every machine. Always.",
    what: "Docker packages your app + all its dependencies into a container — a self-contained box that runs identically on any computer, server, or cloud. Solves 'works on my machine' forever. For OSS tools: users run your tool with ONE command without installing Python, setting up databases, or configuring anything.",
    who: "Docker Inc, founded 2013. Docker Hub has 8M+ images. Used by every tech company for deployment. Standard tool for shipping software in 2026.",
    how: "Write a Dockerfile (recipe: FROM python:3.12, COPY files, RUN pip install, CMD run app) → docker build -t my-tool . (creates image) → docker run my-tool (runs it) → docker push to Docker Hub (share it). Docker Compose: run your app + database + Redis all with one 'docker-compose up' command. For OSS: user just runs 'docker run yourname/your-tool'.",
    tools: ["Docker Desktop (Windows/Mac)", "Docker Hub (free public image hosting)", "docker-compose (multi-service orchestration)", "Dive (inspect image size)", "Portainer (visual Docker management)"],
    resources: ["docs.docker.com/get-started", "docker-curriculum.com (free comprehensive guide)", "play-with-docker.com (browser-based practice)"],
    usedFor: ["OSS tool distribution (one-command install)", "Self-hosting n8n and other tools", "Consistent production deployments", "Region-specific app packaging"],
    timeToLearn: "Running existing images: 1 day. Writing Dockerfiles: 3-4 days.",
    command: "docker run hello-world\ndocker build -t my-app .\ndocker run -p 8000:8000 my-app",
    install: "docker.com/products/docker-desktop → Download → Install",
    color: "#ffb347",
    whyYouNeedIt: "You build OSS tools. Docker is how professional OSS projects distribute software. Also: self-hosting n8n for your automation workflows requires Docker. One Dockerfile = deploy anywhere."
  },
  {
    id: "playwright",
    name: "Playwright / Selenium",
    icon: "🔍",
    category: "OSINT & Scraping",
    categoryColor: "#b388ff",
    level: 80,
    priority: "HIGH",
    tagline: "Automate any browser. Scrape any website. Power your OSINT.",
    what: "Playwright (Microsoft, 2020) and Selenium (2004) are browser automation libraries. They control a real browser programmatically — click buttons, fill forms, navigate pages, extract data. Playwright is the modern choice: faster, more reliable, supports Chrome/Firefox/Safari, has stealth modes to avoid detection.",
    who: "Playwright by Microsoft — 67k+ GitHub stars, 2020. The modern standard for browser automation. Selenium: the classic — been around since 2004, still widely used. Both have Python and JavaScript APIs.",
    how: "playwright.chromium.launch() → page.goto(url) → page.locator('selector').click() → data = page.locator('.result').all_text_contents() → save to file or database. For OSINT: navigate to target site, extract public data, follow links, build data profiles. For scraping lead gen: extract company info, emails, phone numbers from public directories.",
    tools: ["Playwright Python (recommended)", "Playwright Inspector (debug automation visually)", "Bright Data / Oxylabs (proxies for scale)", "playwright-stealth (avoid bot detection)", "BeautifulSoup (parse extracted HTML)"],
    resources: ["playwright.dev/python/docs/intro", "scrapingbee.com/blog/playwright-python", "github.com/microsoft/playwright-python"],
    usedFor: ["OSINT data collection", "Lead gen from public directories", "Automated testing of your own apps", "Monitoring competitor websites", "Data extraction pipelines"],
    timeToLearn: "First scraper working: 1-2 days. Advanced stealth: 1 week.",
    command: "pip install playwright\nplaywright install chromium",
    install: "pip install playwright && playwright install",
    color: "#b388ff",
    whyYouNeedIt: "You build OSINT tools. Playwright is how you automate web intelligence gathering. When a website doesn't have an API, Playwright IS the API."
  },
  {
    id: "phaser",
    name: "Phaser.js / Pygame",
    icon: "🎮",
    category: "Games",
    categoryColor: "#ff6b35",
    level: 75,
    priority: "SITUATIONAL",
    tagline: "Build learning games that run in any browser.",
    what: "Phaser.js is the #1 HTML5 game framework for browser-based 2D games. Built on JavaScript — runs in any browser on any device including mobile. Pygame is Python's game library — great for prototyping desktop games. For your learning games, Phaser is the better choice: publish once, play everywhere.",
    who: "Phaser: 37k+ GitHub stars, actively maintained since 2013. Used by hundreds of indie game devs and educational platforms. Pygame: Python's game standard, perfect for learning and prototyping.",
    how: "Phaser: Create a game config (width, height, physics) → add Scenes (Menu, Game, GameOver) → load assets (sprites, sounds) → write game logic in update() loop → deploy as a static website on Netlify. Phaser + React: embed Phaser game inside a React app for full product experience.",
    tools: ["Phaser 3 (phaser.io)", "Tiled Map Editor (create game maps)", "TexturePacker (sprite sheets)", "Howler.js (game audio)", "Matter.js (physics engine)"],
    resources: ["phaser.io/tutorials", "photonstorm.github.io/phaser3-docs", "github.com/photonstorm/phaser3-examples"],
    usedFor: ["Browser-based learning games", "Educational tools with game mechanics", "Interactive coding tutorials", "Mobile-compatible games via browser"],
    timeToLearn: "First simple game: 1 week. Polished game: 3-4 weeks.",
    command: "npm install phaser\n# Or CDN: <script src='https://cdn.jsdelivr.net/npm/phaser@3/dist/phaser.min.js'>",
    install: "npm install phaser OR use CDN in HTML",
    color: "#ff6b35",
    whyYouNeedIt: "You build learning games. Phaser lets you ship browser games that work on mobile without an app store. React Native for native mobile games, Phaser for browser-based."
  },
];

export const CATEGORIES = [
  "All",
  "Foundation",
  "Core Language",
  "Web Frontend",
  "Mobile",
  "Backend",
  "AI Framework",
  "Voice Stack",
  "Database & Auth",
  "Automation",
  "Automation Backend",
  "Lead Generation",
  "OSINT & Scraping",
  "Games",
  "Payments",
  "OSS & Version Control",
  "AI IDE",
  "Deployment",
];

export const PRIORITY_ORDER = ["CRITICAL", "HIGH", "SITUATIONAL"];
